import { pgTable, text, varchar, integer, boolean, timestamp, jsonb, decimal } from "drizzle-orm/pg-core";

export const studiesRaw = pgTable("studies_raw", {
    nctId: varchar("nct_id", { length: 20 }).primaryKey(),
    briefTitle: text("brief_title"),
    officialTitle: text("official_title"),
    briefSummary: text("brief_summary"),
    detailedDescription: text("detailed_description"),
    overallStatus: varchar("overall_status", { length: 100 }),
    phase: text("phase"),
    studyType: varchar("study_type", { length: 100 }),
    eligibilityCriteriaRaw: text("eligibility_criteria_raw"),
    inclusionCriteriaRaw: text("inclusion_criteria_raw"),
    exclusionCriteriaRaw: text("exclusion_criteria_raw"),
    sex: varchar("sex", { length: 50 }),
    minimumAge: varchar("minimum_age", { length: 50 }),
    maximumAge: varchar("maximum_age", { length: 50 }),
    conditions: jsonb("conditions"),
    contactsJson: jsonb("contacts_json"),
    locationsJson: jsonb("locations_json"),
    leadSponsorName: text("lead_sponsor_name"),
    lastUpdatePostDate: timestamp("last_update_post_date"),
    sourceExtractedAt: timestamp("source_extracted_at"),
    rawLastUpdatedAt: timestamp("raw_last_updated_at"),
    interventionsJson: jsonb("interventions_json"),
    primaryPurpose: text("primary_purpose"),
    masking: text("masking"),
    allocation: text("allocation"),
    primaryOutcomesJson: jsonb("primary_outcomes_json"),
    targetCountries: jsonb("target_countries"),
    isPublishable: boolean("is_publishable"),
    studyFirstSubmittedDate: timestamp("study_first_submitted_date"),
    studyFirstPostedDate: timestamp("study_first_posted_date"),
    startDate: timestamp("start_date"),
    primaryCompletionDate: timestamp("primary_completion_date"),
    completionDate: timestamp("completion_date"),
    statusVerifiedDate: timestamp("status_verified_date"),
    leadSponsorClass: text("lead_sponsor_class"),
    enrollmentCount: integer("enrollment_count"),
    enrollmentType: text("enrollment_type"),
    interventionalModel: text("interventional_model"),
    observationalModel: text("observational_model"),
    timePerspective: text("time_perspective"),
    phaseNumeric: integer("phase_numeric"),
    isLatePhase: boolean("is_late_phase"),
    primaryCondition: text("primary_condition"),
    isRecruiting: boolean("is_recruiting"),
});

export const studiesAi = pgTable("studies_ai", {
    nctId: varchar("nct_id", { length: 20 }).primaryKey().references(() => studiesRaw.nctId),
    titleEs: text("title_es"),
    titleSimpleEs: text("title_simple_es"),
    briefSummaryEs: text("brief_summary_es"),
    keyEligibilityEs: text("key_eligibility_es"),
    structuredEligibilityJson: jsonb("structured_eligibility_json"),
    category: text("category"),
    subcategory: text("subcategory"),
    tags: jsonb("tags"),
    metaTitle: text("meta_title"),
    metaDescription: text("meta_description"),
    slug: text("slug"),
    aiLastUpdatedAt: timestamp("ai_last_updated_at"),
    phaseEs: text("phase_es"),
    studyTypeEs: text("study_type_es"),
    interventionsEs: jsonb("interventions_es"),
    primaryOutcomeEs: text("primary_outcome_es"),
    genderTarget: text("gender_target"),
});

export const studiesCustom = pgTable("studies_custom", {
    nctId: varchar("nct_id", { length: 20 }).primaryKey().references(() => studiesRaw.nctId),
    imageUrl: text("image_url"),
    videoUrl: text("video_url"),
    videoScript: text("video_script"),
    pricingPlan: text("pricing_plan"),
    pricePerLead: decimal("price_per_lead"),
    isFeatured: boolean("is_featured").default(false),
    featurePriority: integer("feature_priority").default(0),
    commentMd: text("comment_md"),
    subscriptionStart: timestamp("subscription_start"),
    subscriptionEnd: timestamp("subscription_end"),
    createdAt: timestamp("created_at").defaultNow(),
    updatedAt: timestamp("updated_at").defaultNow(),
});
